[[custom_groups]]
name = "🔰 انتخاب نود"
type = "select"
rule = ["[]♻️ انتخاب خودکار", "[]🎯 مستقیم", ".*"]

[[custom_groups]]
name = "♻️ انتخاب خودکار"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "🎥 NETFLIX"
type = "select"
rule = [
    "[]🔰 انتخاب نود",
    "[]♻️ انتخاب خودکار",
    "[]🎯 مستقیم",
    ".*"
]

[[custom_groups]]
name = "⛔️ مسدود کردن تبلیغات"
type = "select"
rule = ["[]🛑 مسدود",
"[]🎯 مستقیم",
"[]🔰 انتخاب نود"
]

[[custom_groups]]
name = "🚫 Hijacking"
type = "select"
rule = ["[]🛑 مسدود",
"[]🎯 مستقیم",
"[]🔰 انتخاب نود"]

[[custom_groups]]
name = "🌍 رسانه های خارجی"
type = "select"
rule = ["[]🔰 انتخاب نود",
"[]♻️ انتخاب خودکار",
"[]🎯 مستقیم",
".*"]

[[custom_groups]]
name = "🌏 رسانه های داخلی"
type = "select"
rule = ["[]🎯 مستقیم",
"(HGC|HKBN|PCCW|HKT|深台|彰化|新北|台|hk|港|tw)",
"[]🔰 انتخاب نود"]

[[custom_groups]]
name = "Ⓜ️ مایکروسافت"
type = "select"
rule = ["[]🎯 مستقیم",
"[]🔰 انتخاب نود",
".*"]

[[custom_groups]]
name = "📲 تلگرام"
type = "select"
rule = ["[]🔰 انتخاب نود",
"[]🎯 مستقیم",
".*"]

[[custom_groups]]
name = "🍎 اپل"
type = "select"
rule = ["[]🔰 انتخاب نود",
"[]🎯 مستقیم",
"[]♻️ انتخاب خودکار",
".*"]

[[custom_groups]]
name = "🎯 مستقیم"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "🛑 مسدود"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = ["[]🔰 انتخاب نود",
"[]🎯 مستقیم",
"[]♻️ انتخاب خودکار",
".*"]
